---
title: 'Домашка для тех, кто еще не устал'
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    highlight: pygments
  # df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Задача 1: КумСум 

Создать матрицу, каждый элемент которой будет равен кумулятивной сумме предыдущих, обход матрицы совершать методом под названием змейка (на допе был пример).

Алгоритм, для тех кто забыл:

1. Каждый следующий элемент должен быть равен сумме предыдущих + сам элемент

2. Элементы берутся следующим образом: идём от 1;1 элемента вправо до последнего столбца, затем идём вниз до последней строчки. Затем идем влево до первого столбца, далее идём вверх до первой строчки.

**Замечание:** Алгоритм должен работать для квадратной матрицы

**Дополнительно:** Для матрицы любого размера.

Например, на вход идет:
$$
\left(\begin{array}{cc} 
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1\\
\end{array}\right)
$$
Получаем на выход:
$$
\left(\begin{array}{cc} 
1 & 2 & 3 & 4\\
12 & 13 & 14 & 5\\
11 & 16 & 15 & 6\\
10 & 9 & 8 & 7\\
\end{array}\right)
$$

## Задача 2: 

Из исходной матрицы составить другую аналогичного размера так, чтобы каждый элемент новой матрицы состоял из суммы четырёх соседних элементов (сверху, слева, снизу, справа). Если элемент находится с краю, то элементы берутся с другой стороны на границе.

Пример:

Вход:

$$
\left(\begin{array}{cc} 
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{array}\right)
$$
Выход:

$$
\left(\begin{array}{cc} 
2+4 & 1+3+5 & 2+6 \\
1+5+7 & 2+6+8+4 & 5+3+9 \\
4+8 & 7+5+9 & 6+8 \\
\end{array}\right)
$$
