---
title: 'Домашка №2'
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    highlight: pygments
  # df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Задача 1: Гусеничка: (1.5 балла, решали на семинаре)

Гусеничка пытается взобраться на дерево высоты $100$ м. За день гусеничка взбирается всего лишь на $5$ метров вверх. Однако ночью гусеница отдыхает и скользит вниз на $2$ метра. За сколько дней, гусеница таки доползёт до самого верха. (задача решалась, надо обернуть в функцию и подсчитать сложность)

## Задача 2: reverse (1.5  балла, решали на семинаре)

Необходимо перевернуть массив. 

**Пример:**

$(1,2,3,4,5)$ нужно представить в $(5,4,3,2,1)$. 

Пользоваться встроенными функциями нельзя. (задача решалась, надо обернуть в функцию и подсчитать сложность)

## Задача 3: До минус двух (1.5  балла, решали на семинаре)

Задается любое натуральное число $n$. Необходимо создать массив чисел от $n$ до $-2$.

**Пример:** 

Дано: $4$  
Ответ: $4$ $3$ $2$ $1$ $0$ $-1$ $-2$.  

Задача решалась и даже писалась функция. Можно получить халявные баллы за сложность.

## Подзадача 4`: (3 балла)

Написать функцию которая проверяет есть ли данный элемент $a$ в массиве. То есть на вход идет число и массив. Ответ функции `TRUE` или `FALSE`.

## Задача 4: (5 баллов)

Дан массив. Необходимо создать новый массив с уникальными элементами из данного. Пользоваться встроенными функциями нельзя. Можно получить $+1$ балл за определение сложности, $+2$ балла за самый оптимальный алгоритм.

**Пример:** 

Дано: $(1,5,6,1,1,3,5,5)$  
Ответ: $(1,5,6,3)$.  


**Замечание:** Есть мнение что её надо решать после задачи 4`

**Доп на 2,5 балла:** Вывести все **не**уникальные элементы массива.

**Доп на 2 балла (проверка самого главного инструмента программиста):** Найти исходный код функции `unique`, которая быстро решает эту задачу, возможно, код будет написан не на $R$, а на другом языке программирования, это нестрашно, ведь вам не надо понимать этот код, достаточно просто скинуть его. Напоминаю, что пользоваться этой функцией при решении нельзя.

## Задача 5: наша любимая рекурсия (5 баллов)

Дано действительное положительное число $а$ и целое неотрицательное число $n$. Вычислить $а^n$, не используя циклы, возведение в степень и другие встроенные функции. Можно использовать только рекуррентное соотношение $a^n = a \cdot a^{n-1}$.

